# -*- coding: utf-8 -*-
"""Password Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvWYH3TZu_nkEXhbXzxTkb6u8FEcjUdk
"""

import random
import string
def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))
    return password
try:
    length = int(input("Enter desired password length: "))
    if length <= 0:
        print("Length should be greater than 0.")
    else:
        print("Generated Password:", generate_password(length))
except ValueError:
    print("Please enter a valid number.")